/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp SystemStatus.xml -a SystemStatusAdaptor -c SystemStatusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "SystemStatusAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SystemStatusAdaptor
 */

SystemStatusAdaptor::SystemStatusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SystemStatusAdaptor::~SystemStatusAdaptor()
{
    // destructor
}

int SystemStatusAdaptor::getHddStatus()
{
    // handle method call vp9.system_status.getHddStatus
    int out0;
    QMetaObject::invokeMethod(parent(), "getHddStatus", Q_RETURN_ARG(int, out0));
    return out0;
}

int SystemStatusAdaptor::getNetworkStatus()
{
    // handle method call vp9.system_status.getNetworkStatus
    int out0;
    QMetaObject::invokeMethod(parent(), "getNetworkStatus", Q_RETURN_ARG(int, out0));
    return out0;
}

